---

- name: 'make sure .bashrc exists'
  become: no
  file: path=~/.bashrc state=file
  tags:
    - postgres
    - el_postgres_role
    - bash

- name: 'amend path variable'
  lineinfile: dest=~/.bashrc
              line='export PATH=$PATH:/usr/pgsql-9.5/bin'
              state=present
  tags:
    - postgres
    - el_postgres_role
    - bash

- name: 'make sure .bash_profile exists'
  become: yes
  become_user: postgres
  file: path=/var/lib/pgsql/.bash_profile state=file
  tags:
    - postgres
    - el_postgres_role
    - bash

- name: 'amend path variable'
  become: yes
  become_user: postgres
  lineinfile: dest=/var/lib/pgsql/.bash_profile
              line='export PATH=$PATH:/usr/pgsql-9.5/bin'
              state=present
  tags:
    - postgres
    - el_postgres_role
    - bash

- name: 'init postgresql database'
  command: /usr/pgsql-9.5/bin/postgresql95-setup initdb creates=/var/lib/pgsql/9.5/data/postgresql.conf
  become: yes
  notify:
    - restart postgresql-9.5
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  tags:
    - install
    - init
    - postgres
    - el_postgres_role

- name: 'ensure postgresql is running automatically at boot'
  service: name=postgresql-9.5 enabled=yes
  become: yes
  when: ansible_os_family == "RedHat"
  tags:
    - install
    - postgres
    - el_postgres_role

- name: 'configure pg_hba.conf'
  template: src={{ your_template_path | default() }}pg_hba.conf.j2 dest=/var/lib/pgsql/9.5/data/pg_hba.conf backup=no
            owner=postgres
  become: yes
  notify:
    - restart postgresql-9.5
  tags:
    - config
    - postgres
    - el_postgres_role
    - replica

- name: 'copy start_pg_slave.sh'
  template: src=start_pg_slave.sh.j2
                 dest=/usr/local/bin/start_pg_slave.sh
                 backup=no
                 owner=root mode=0700
  become: yes
  when: role is defined and role == "slave"
  tags:
    - config
    - postgres
    - el_postgres_role
    - replica

- name: 'unset ip to listen on to ipv4 localhost'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              insertbefore='^#listen_addresses'
              line="listen_addresses = '127.0.0.1'"
              state=absent
  tags:
    - config
    - postgres
    - el_postgres_role

- name: 'see if iptables file exists'
  stat: path=/etc/sysconfig/iptables
  register: iptables
  tags:
    - postgres
    - el_postgres_role

- name: 'fix "postgresql" in /etc/sysconfig/iptables file'
  become: yes
  lineinfile: dest=/etc/sysconfig/iptables
              line='-A INPUT -p tcp -m tcp --dport 5432 -j ACCEPT'
              state=present
              insertbefore=^COMMIT
  notify: restart iptables
  when: iptables is defined and iptables.stat.exists
  tags:
    - config
    - iptables
    - postgres
    - el_postgres_role

- name: 'set listen on on ipv4 addresses'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertbefore='^#listen_addresses'
              line="listen_addresses = '*'" state=present
  tags:
    - postgres
    - el_postgres_role

- name: 'set replication setting: wal_level'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertafter='^listen_addresses'
              line="wal_level = hot_standby" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'set replication setting: max_wal_senders'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf insertafter='^#max_wal_senders'
              line="max_wal_senders = 3" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'set replication setting: checkpoint_segments'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertafter='^#checkpoint_segments'
              line="checkpoint_segments = 8" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'set replication setting: wal_keep_segments'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertafter='^#wal_keep_segments'
              line="wal_keep_segments = 8" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'set replication setting: hot_standby'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertafter='^wal_keep_segments'
              line="hot_standby = on" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'set replication setting: archive_mode'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertafter='^#archive_mode'
              line="archive_mode = on" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'set replication setting: archive_command'
  become: yes
  lineinfile: dest=/var/lib/pgsql/9.5/data/postgresql.conf insertafter='^#archive_command'
              line="archive_command = 'cd .'" state=present
  tags:
    - postgres
    - el_postgres_role
    - replica

- name: 'startup postgres'
  service: name=postgresql-9.5 state=started
  when: role is undefined or role == "master"
  tags:
    - postgres
    - el_postgres_role
    - config
    - pguser

- name: 'initialize the postgresql user'
  postgresql_user: name='{{ el_postgres_user }}' role_attr_flags='CREATEDB,CREATEROLE'
  when: role is undefined or role == "master"
  become: yes
  register: create_pg_user
  tags:
    - postgres
    - el_postgres_role
    - pguser

- name: 'set the password for the postgres user'
  postgresql_user: name='{{ el_postgres_user }}' password="{{ el_postgres_pass }}"
  become: yes
  when: role is undefined or role == "master"
  tags:
    - postgres
    - el_postgres_role
    - pguser

- name: 'initialize the replicator user'
  postgresql_user: name='replicator' role_attr_flags='REPLICATION' password="{{ el_postgres_pass }}"
  when: role is undefined or role == "master"
  tags:
    - postgres
    - el_postgres_role
    - pguser
    - replica

- name: 'start the slave with the script in /usr/local/bin'
  expect:
    command: /usr/local/bin/start_pg_slave.sh
    responses:
      Password: "{{ el_postgres_pass }}"
  when: role is defined and role == "slave"
  tags:
    - postgres
    - el_postgres_role
    - replica
    - startslave
